services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    image: recallcode-client
    container_name: recallcode-client
    restart: always
    expose:
      - "80" 
    depends_on:
      - backend
    networks:
      - recallcode-network  

  docs:
    build:
      context: ./RecallCode-Docs
      dockerfile: Dockerfile
    image: recallcode-docs  
    container_name: recallcode-docs
    expose:
      - "80"
    depends_on:
      - backend
    networks:
      - recallcode-network     

  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: recallcode-backend
    image: recallcode-backend
    restart: always
    env_file:
      - ./Server/.env
    expose:
      - "7000"
    depends_on:
      - mongo
    networks:
      - recallcode-network

  nginx-proxy:
    image: nginx:alpine
    container_name: recallcode-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - docs
      - backend
    networks:
      - recallcode-network  
    restart: always

  mongo:
    image: mongo
    container_name: recallcode-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - recallcode-network

volumes:
  mongo_data:

networks:
  recallcode-network:
    driver: bridge