services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: recallcode-backend 
    container_name: recallcode-backend
    ports:
      - "7000:7000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - recallcode-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: recallcode-client 
    container_name: recallcode-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    depends_on:
      - server
    networks:
      - recallcode-network
  
  docs:
    build:
      context: ./RecallCode-Docs
      dockerfile: Dockerfile.dev
    image: recallcode-docs  
    container_name: recallcode-docs
    ports:
      - "5174:5174"
    depends_on:
      - server
    networks:
      - recallcode-network    

  mongo:
    image: mongo
    container_name: recallcode-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - recallcode-network

volumes:
  mongo_data:

networks:
  recallcode-network:
    driver: bridge
